[package]
name = "example"
version = "0.1.0"
authors = ["John Rees <john@bitsushi.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lunatic = "0.3.10"
